import type { AngularRelease } from '../angular-releases';

export const angular17Release: AngularRelease = {
  key: '17',
  label: 'Angular 17',
  order: 17,
  year: 'November 8, 2023',
  theme: 'New template control flow',
  summary:
    'Angular 17 changed how modern templates look, adding built-in control flow and deferrable views.',
  features: [
    {
      title: 'Built-in control flow',
      category: 'Templates',
      impact: 'Major',
      description:
        '@if, @for, and @switch reduced the need for microsyntax directives like *ngIf and *ngFor.',
    },
    {
      title: 'Deferrable views',
      category: 'Performance',
      impact: 'Major',
      description:
        '@defer let templates define lazy-loaded UI islands with loading, placeholder, and error states.',
    },
    {
      title: 'Application builder modernization',
      category: 'Tooling',
      impact: 'Important',
      description: 'The CLI moved toward faster esbuild and Vite-powered development workflows.',
    },
    {
      title: 'angular.dev documentation launch',
      category: 'Tooling',
      impact: 'Important',
      description:
        'Angular 17 introduced the new angular.dev documentation experience and a clearer modern learning path.',
    },
    {
      title: 'Standalone generated by default',
      category: 'Migration',
      impact: 'Important',
      description:
        'ng generate created standalone components by default, making the new architecture the normal authoring path.',
    },
    {
      title: 'Hydration stable for SSR',
      category: 'SSR',
      impact: 'Major',
      description:
        'Hydration became stable and was enabled by default for new server-rendered applications.',
    },
    {
      title: 'Dependency injection debugging in DevTools',
      category: 'Tooling',
      impact: 'Important',
      description:
        'Angular DevTools gained better visibility into dependency injection, helping teams inspect provider relationships during debugging.',
    },
    {
      title: '@for performance improvements',
      category: 'Performance',
      impact: 'Important',
      description:
        'The new @for block used a more optimized diffing strategy than *ngFor for many list-rendering cases.',
    },
  ],
  examples: [
    {
      title: 'Modern template flow',
      language: 'html',
      code: `@if (user(); as profile) {
  <h2>{{ profile.name }}</h2>
} @else {
  <p>Choose a user</p>
}

@for (item of items(); track item.id) {
  <app-item [item]="item" />
}`,
      explanation:
        'The new syntax is easier to scan and gives Angular a stronger foundation for template type checking and performance.',
    },
    {
      title: 'Deferrable view with loading state',
      language: 'html',
      code: `@defer (on viewport) {
  <app-chart />
} @loading {
  <app-spinner />
}`,
      explanation:
        '@defer lets a template describe lazy UI islands and their loading states without hand-written route boundaries.',
    },
  ],
};
